# Generated by Django 5.0.7 on 2024-07-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('no_pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='books/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
