# Generated by Django 5.0.7 on 2024-07-31 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0003_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='no_pages',
            new_name='pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.author'),
        ),
    ]
